services:
  volum:
    build: .
    container_name: volum
    ports:
      - "8090:8090"
    volumes:
      - ./storage:/storage
      - ./data:/data
    environment:
      - VOLUM_ROOTS=/storage
      - VOLUM_DB=/data/volum.db
      - VOLUM_PORT=8090
      # Set these to enable login and protect write APIs.
      - VOLUM_ADMIN_PASSWORD=123qwe
      - VOLUM_READONLY_PASSWORD=123qwe
      - VOLUM_SESSION_SECRET=b4z/gyKWN2iclkXBwJ+KD5GLOQ1hPdx8sf4Mmyz3kjA=
    restart: unless-stopped
